# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimise_mvnormal_saving <- function(x, Q, nbs, extended_nbs, alpha_dense = 0.0, beta = 0.0, alpha_sparse = 0.0) {
    .Call(`_mvcapaCor_optimise_mvnormal_saving`, x, Q, nbs, extended_nbs, alpha_dense, beta, alpha_sparse)
}

dense_mvnormal_savings <- function(mean_x, Q, n) {
    .Call(`_mvcapaCor_dense_mvnormal_savings`, mean_x, Q, n)
}

main1 <- function() {
    .Call(`_mvcapaCor_main1`)
}

main2 <- function() {
    .Call(`_mvcapaCor_main2`)
}

mvcapa_cor <- function(x, Q, b = 1, b_point = 1, min_seg_len = 2L, max_seg_len = 100000000L) {
    .Call(`_mvcapaCor_mvcapa_cor`, x, Q, b, b_point, min_seg_len, max_seg_len)
}

lower_nbs <- function(A) {
    .Call(`_mvcapaCor_lower_nbs`, A)
}

extended_lower_nbs <- function(nbs) {
    .Call(`_mvcapaCor_extended_lower_nbs`, nbs)
}

test_precision_copy <- function(A) {
    invisible(.Call(`_mvcapaCor_test_precision_copy`, A))
}

test_precision_move <- function(A) {
    invisible(.Call(`_mvcapaCor_test_precision_move`, A))
}

single_mvnormal_changepoint <- function(x, Q, b = 1, min_seg_len = 2L) {
    .Call(`_mvcapaCor_single_mvnormal_changepoint`, x, Q, b, min_seg_len)
}

