# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hash_map_test <- function() {
    invisible(.Call(`_mvcapaCor_hash_map_test`))
}

optimise_savings <- function(Q, b, penalty_components, extended_nbs_list) {
    .Call(`_mvcapaCor_optimise_savings`, Q, b, penalty_components, extended_nbs_list)
}

optimise_savings_list <- function(Q, b, penalty_components, extended_nbs_list) {
    .Call(`_mvcapaCor_optimise_savings_list`, Q, b, penalty_components, extended_nbs_list)
}

list_test <- function(L) {
    invisible(.Call(`_mvcapaCor_list_test`, L))
}

seq_int <- function(start, end) {
    .Call(`_mvcapaCor_seq_int`, start, end)
}

test_map <- function() {
    .Call(`_mvcapaCor_test_map`)
}

test_ubt <- function(n_levels = 4L) {
    invisible(.Call(`_mvcapaCor_test_ubt`, n_levels))
}

which_max_test <- function() {
    invisible(.Call(`_mvcapaCor_which_max_test`))
}

test_rev_vec <- function() {
    invisible(.Call(`_mvcapaCor_test_rev_vec`))
}

test_accu <- function() {
    .Call(`_mvcapaCor_test_accu`)
}

optimise_savings_vec_old <- function(Q, b, penalty_components, extended_nbs_list) {
    .Call(`_mvcapaCor_optimise_savings_vec_old`, Q, b, penalty_components, extended_nbs_list)
}

test_grow_tree <- function(Q, b, penalty_components, extended_nbs_list) {
    invisible(.Call(`_mvcapaCor_test_grow_tree`, Q, b, penalty_components, extended_nbs_list))
}

optimise_savings_old <- function(Q, b, penalty_components, extended_nbs_list) {
    .Call(`_mvcapaCor_optimise_savings_old`, Q, b, penalty_components, extended_nbs_list)
}

