# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

capacc <- function(x, Q, b = 1, b_point = 1, min_seg_len = 2L, max_seg_len = 100000000L) {
    .Call(`_capacc_capacc`, x, Q, b, b_point, min_seg_len, max_seg_len)
}

capacc_sparse <- function(x, Q, b = 1, b_point = 1, min_seg_len = 2L, max_seg_len = 100000000L) {
    .Call(`_capacc_capacc_sparse`, x, Q, b, b_point, min_seg_len, max_seg_len)
}

optimise_mvnormal_saving <- function(x, Q, nbs, extended_nbs, alpha_dense = 0.0, beta = 0.0, alpha_sparse = 0.0) {
    .Call(`_capacc_optimise_mvnormal_saving`, x, Q, nbs, extended_nbs, alpha_dense, beta, alpha_sparse)
}

dense_mvnormal_savings <- function(mean_x, Q, n) {
    .Call(`_capacc_dense_mvnormal_savings`, mean_x, Q, n)
}

optimise_mvnormal_lr <- function(cpt, x, Q, b = 1) {
    .Call(`_capacc_optimise_mvnormal_lr`, cpt, x, Q, b)
}

cptcc <- function(x, Q, b = 1, min_seg_len = 2L) {
    .Call(`_capacc_cptcc`, x, Q, b, min_seg_len)
}

main1 <- function() {
    .Call(`_capacc_main1`)
}

main2 <- function() {
    .Call(`_capacc_main2`)
}

lower_nbs <- function(A) {
    .Call(`_capacc_lower_nbs`, A)
}

extended_lower_nbs <- function(nbs) {
    .Call(`_capacc_extended_lower_nbs`, nbs)
}

test_precision_copy <- function(A) {
    invisible(.Call(`_capacc_test_precision_copy`, A))
}

test_precision_move <- function(A) {
    invisible(.Call(`_capacc_test_precision_move`, A))
}

